// Generated by scripts/update-verified-data.mjs
// This file records source checks. It does not turn unverified source changes into game facts.

export const sourceWatch = [
  {
    "label": "Steam store page",
    "url": "https://store.steampowered.com/app/2261430/LumenTale_Memories_of_Trey/",
    "trust": "official",
    "use": "Release status, official description, tags, and store metadata.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-05T04:15:14.065Z",
    "responseMs": 515,
    "contentLength": 138535,
    "hash": "b3a5e7475773816bffe83801eb61d8d19b53b2768f90bfad7fd7e5b723a6d8b1",
    "changed": true
  },
  {
    "label": "Steam news",
    "url": "https://steamcommunity.com/app/2261430/allnews/",
    "trust": "official",
    "use": "Official news, starters, evolutions, systems, and patch notes.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-05T04:15:14.482Z",
    "responseMs": 417,
    "contentLength": 87578,
    "hash": "5d51e01392c93aed6984f1519b25aa3daa96938ac75fb2470d08f1fa1214e344",
    "changed": true
  },
  {
    "label": "Official Animon page",
    "url": "https://www.beehivegamestudios.com/lumentale/animon/",
    "trust": "official",
    "use": "Official Animon list and facts when visible.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-05T04:15:15.051Z",
    "responseMs": 568,
    "contentLength": 26643,
    "hash": "f0ab0812f7152f8a842ed9438e4e02bb3b9e3c9784fcfe418d9d9a66017bc050",
    "changed": false
  },
  {
    "label": "Official site homepage",
    "url": "https://www.beehivegamestudios.com/lumentale/",
    "trust": "official",
    "use": "Official site overview, game description, and feature list.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-05T04:15:15.175Z",
    "responseMs": 124,
    "contentLength": 59655,
    "hash": "8ce5e0828d24dfaae6057e1aab5c1c2e45d46a64df74306d80e1eee68e49517a",
    "changed": false
  },
  {
    "label": "Game8 hub",
    "url": "https://game8.co/games/LumenTale-Memories-of-Trey",
    "trust": "community",
    "use": "Lead source only unless the page explicitly lists verifiable data.",
    "ok": true,
    "status": 202,
    "checkedAt": "2026-08-05T04:15:15.257Z",
    "responseMs": 82,
    "contentLength": 0,
    "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "changed": false
  },
  {
    "label": "Neoseeker Animon index",
    "url": "https://www.neoseeker.com/lumentale-memories-of-trey/Animon",
    "trust": "community",
    "use": "Community Animon index. Lead source for name verification.",
    "ok": false,
    "status": 403,
    "checkedAt": "2026-08-05T04:15:15.383Z",
    "responseMs": 126,
    "contentLength": 1149,
    "hash": "9692caa80a73109b6737afba9226ba599b03b9a31416a69b0d9a58d2f6c016e7",
    "changed": true
  },
  {
    "label": "Reddit LumenTale",
    "url": "https://www.reddit.com/r/LumenTale/",
    "trust": "community",
    "use": "Lead source only; never official confirmation by itself.",
    "ok": false,
    "status": 403,
    "checkedAt": "2026-08-05T04:15:15.440Z",
    "responseMs": 57,
    "contentLength": 88859,
    "hash": "b046ca2fdfe3cbd728e609fa21398a1da56349bffa1bf0725182381b8aacfae9",
    "changed": false
  }
] as const

export function getLastSourceCheckDate(): string {
  return 'August 5, 2026'
}
