// Generated by scripts/update-verified-data.mjs
// This file records source checks. It does not turn unverified source changes into game facts.

export const sourceWatch = [
  {
    "label": "Steam store page",
    "url": "https://store.steampowered.com/app/2261430/LumenTale_Memories_of_Trey/",
    "trust": "official",
    "use": "Release status, official description, tags, and store metadata.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-07-18T03:59:55.012Z",
    "responseMs": 385,
    "contentLength": 138767,
    "hash": "89679ac9268f1a860e3e4b9b6677412464a5fa9a1fc7af21e510ee37dc20d515",
    "changed": true
  },
  {
    "label": "Steam news",
    "url": "https://steamcommunity.com/app/2261430/allnews/",
    "trust": "official",
    "use": "Official news, starters, evolutions, systems, and patch notes.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-07-18T03:59:55.430Z",
    "responseMs": 417,
    "contentLength": 87035,
    "hash": "17fce582aad7e49ce0bfa2d167c7457ee3c043aa8d759d75c072e3de3ad0d89c",
    "changed": true
  },
  {
    "label": "Official Animon page",
    "url": "https://www.beehivegamestudios.com/lumentale/animon/",
    "trust": "official",
    "use": "Official Animon list and facts when visible.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-07-18T03:59:56.346Z",
    "responseMs": 916,
    "contentLength": 26643,
    "hash": "f0ab0812f7152f8a842ed9438e4e02bb3b9e3c9784fcfe418d9d9a66017bc050",
    "changed": false
  },
  {
    "label": "Official site homepage",
    "url": "https://www.beehivegamestudios.com/lumentale/",
    "trust": "official",
    "use": "Official site overview, game description, and feature list.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-07-18T03:59:56.519Z",
    "responseMs": 173,
    "contentLength": 59655,
    "hash": "8ce5e0828d24dfaae6057e1aab5c1c2e45d46a64df74306d80e1eee68e49517a",
    "changed": false
  },
  {
    "label": "Game8 hub",
    "url": "https://game8.co/games/LumenTale-Memories-of-Trey",
    "trust": "community",
    "use": "Lead source only unless the page explicitly lists verifiable data.",
    "ok": true,
    "status": 202,
    "checkedAt": "2026-07-18T03:59:56.543Z",
    "responseMs": 24,
    "contentLength": 0,
    "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "changed": false
  },
  {
    "label": "Neoseeker Animon index",
    "url": "https://www.neoseeker.com/lumentale-memories-of-trey/Animon",
    "trust": "community",
    "use": "Community Animon index. Lead source for name verification.",
    "ok": false,
    "status": 403,
    "checkedAt": "2026-07-18T03:59:56.595Z",
    "responseMs": 52,
    "contentLength": 1149,
    "hash": "b2119fb2e722dc9abff4187dce7fc1df445a4caf0b39bfaca7683c5adee8daa6",
    "changed": true
  },
  {
    "label": "Reddit LumenTale",
    "url": "https://www.reddit.com/r/LumenTale/",
    "trust": "community",
    "use": "Lead source only; never official confirmation by itself.",
    "ok": false,
    "status": 403,
    "checkedAt": "2026-07-18T03:59:56.617Z",
    "responseMs": 22,
    "contentLength": 88859,
    "hash": "b046ca2fdfe3cbd728e609fa21398a1da56349bffa1bf0725182381b8aacfae9",
    "changed": false
  }
] as const

export function getLastSourceCheckDate(): string {
  return 'July 18, 2026'
}
