// Generated by scripts/update-verified-data.mjs
// This file records source checks. It does not turn unverified source changes into game facts.

export const sourceWatch = [
  {
    "label": "Steam store page",
    "url": "https://store.steampowered.com/app/2261430/LumenTale_Memories_of_Trey/",
    "trust": "official",
    "use": "Release status, official description, tags, and store metadata.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-14T03:25:47.029Z",
    "responseMs": 346,
    "contentLength": 138977,
    "hash": "5405a57f6f84c65a095f737cf2c7c10f500d9bf7f2ce1db8e0edaecea1bdb6b3",
    "changed": true
  },
  {
    "label": "Steam news",
    "url": "https://steamcommunity.com/app/2261430/allnews/",
    "trust": "official",
    "use": "Official news, starters, evolutions, systems, and patch notes.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-14T03:25:47.356Z",
    "responseMs": 326,
    "contentLength": 87578,
    "hash": "d64b1be4de23c28f052a4b48f0f4c0c428f450d0db08d2c93852e3cef08c8a39",
    "changed": true
  },
  {
    "label": "Official Animon page",
    "url": "https://www.beehivegamestudios.com/lumentale/animon/",
    "trust": "official",
    "use": "Official Animon list and facts when visible.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-14T03:25:48.051Z",
    "responseMs": 695,
    "contentLength": 26643,
    "hash": "f0ab0812f7152f8a842ed9438e4e02bb3b9e3c9784fcfe418d9d9a66017bc050",
    "changed": false
  },
  {
    "label": "Official site homepage",
    "url": "https://www.beehivegamestudios.com/lumentale/",
    "trust": "official",
    "use": "Official site overview, game description, and feature list.",
    "ok": true,
    "status": 200,
    "checkedAt": "2026-08-14T03:25:48.227Z",
    "responseMs": 176,
    "contentLength": 59655,
    "hash": "8ce5e0828d24dfaae6057e1aab5c1c2e45d46a64df74306d80e1eee68e49517a",
    "changed": false
  },
  {
    "label": "Game8 hub",
    "url": "https://game8.co/games/LumenTale-Memories-of-Trey",
    "trust": "community",
    "use": "Lead source only unless the page explicitly lists verifiable data.",
    "ok": true,
    "status": 202,
    "checkedAt": "2026-08-14T03:25:48.261Z",
    "responseMs": 34,
    "contentLength": 0,
    "hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "changed": false
  },
  {
    "label": "Neoseeker Animon index",
    "url": "https://www.neoseeker.com/lumentale-memories-of-trey/Animon",
    "trust": "community",
    "use": "Community Animon index. Lead source for name verification.",
    "ok": false,
    "status": 403,
    "checkedAt": "2026-08-14T03:25:48.286Z",
    "responseMs": 25,
    "contentLength": 1149,
    "hash": "f36b879e7782bc6782f58433c78379192c01b331b632e79aa303b73c0806f50d",
    "changed": true
  },
  {
    "label": "Reddit LumenTale",
    "url": "https://www.reddit.com/r/LumenTale/",
    "trust": "community",
    "use": "Lead source only; never official confirmation by itself.",
    "ok": false,
    "status": 403,
    "checkedAt": "2026-08-14T03:25:48.317Z",
    "responseMs": 31,
    "contentLength": 88859,
    "hash": "b046ca2fdfe3cbd728e609fa21398a1da56349bffa1bf0725182381b8aacfae9",
    "changed": false
  }
] as const

export function getLastSourceCheckDate(): string {
  return 'August 14, 2026'
}
