// Generated by scripts/update-verified-data.mjs
// Official-source checks used to unlock verified LumenTale content.

export const officialSourceMatches = [
  {
    "name": "Mewaii",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Vortail",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Ozelash",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Salabel",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Queccha",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Maidelly",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Furtex",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Kouzear",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Vilender",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Quequator",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Lampecko",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Cocopa",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Mushwick",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Owaxle",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Boobat",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Flowende",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Flobesque",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Lanpit",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Melotica",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Quidvil",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Puffella",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Lopyuna",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Rainagon",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Mediglee",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Dionybble",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Chompuff",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Ghorious",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Almyuna",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Bonkey",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Tamboad",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Smellwing",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Toxigall",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Deniuli",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Katamos",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Arct-Rex",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Nanafin",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Mollupom",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Obsidedge",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Iotamor",
    "officialMatches": [],
    "status": "not-found"
  },
  {
    "name": "Pymant",
    "officialMatches": [],
    "status": "not-found"
  }
] as const

export const contentUnlocks = [] as const

export function getVerifiedGameDataDate(): string {
  return 'June 1, 2026'
}
